name: Deploy to VM and ACR

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the Ubuntu runner

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository code

    # Step 2: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: qhinhprd.azurecr.io  # Your ACR login server
        username: ${{ secrets.ACR_USERNAME }}  # Username from GitHub Secrets
        password: ${{ secrets.ACR_PASSPHRASE }}  # Password from GitHub Secrets

    # Step 3: Build and push backend image
    - name: Build and push backend Docker image
      run: |
        cd application-my/fastapi-backend
        docker build -t qhinhprd.azurecr.io/fastapi-backend:latest .
        docker push qhinhprd.azurecr.io/fastapi-backend:latest

    # Step 4: Build and push frontend image
    - name: Build and push frontend Docker image
      run: |
        cd application-my/react-frontend
        docker build -t qhinhprd.azurecr.io/react-frontend:latest .
        docker push qhinhprd.azurecr.io/react-frontend:latest

    # Step 5: Deploy to VM
    - name: Deploy to Azure VM
      with:
        host: ${{ secrets.VM_IP }}  # VM IP address from GitHub Secrets
        username: ${{ secrets.VM_USERNAME }}  # VM user from GitHub Secrets
        password: ${{ secrets.VM_PASSPHRASE }}  # Optional: VM password
        
        script: |
          # Log in to Azure Container Registry on the VM
          az acr login --name qhinhprd --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSPHRASE }}
          
          # Pull and run backend Docker container
          docker pull qhinhprd.azurecr.io/fastapi-backend:latest
          docker run -d --name backend -p 8000:8000 qhinhprd.azurecr.io/fastapi-backend:latest
          
          # Pull and run frontend Docker container
          docker pull qhinhprd.azurecr.io/react-frontend:latest
          docker run -d --name frontend -p 3000:3000 qhinhprd.azurecr.io/react-frontend:latest
