name: Deploy to VM and ACR

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the Ubuntu runner

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository code

    # Step 2: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: qhinhprd.azurecr.io  # Your ACR login server
        username: ${{ secrets.ACR_USERNAME }}  # Username from GitHub Secrets
        password: ${{ secrets.ACR_PASSWORD }}  # Use the correct secret for ACR password

    # Step 3: Build and push frontend Docker image
    - name: Build and push frontend Docker image
      run: |
        # Update the path to reflect the correct location of the Dockerfile
        docker build -t qhinhprd.azurecr.io/react-frontend:latest ./  # Building from the root folder
        docker push qhinhprd.azurecr.io/react-frontend:latest

    # Step 4: Deploy to Azure VM
    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.6  # Use the SSH action to connect to the VM
      with:
        host: ${{ secrets.VM_IP }}  # VM IP address from GitHub Secrets
        username: ${{ secrets.VM_USERNAME }}  # VM username from GitHub Secrets
        password: ${{ secrets.VM_PASSPHRASE }}  # VM passphrase from GitHub Secrets
        port: 22  # Default SSH port
        script: |
          # Log in to Azure Container Registry on the VM
          az acr login --name qhinhprd --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
          
          # Pull and run frontend Docker container
          docker pull qhinhprd.azurecr.io/react-frontend:latest
          docker run -d --name frontend -p 3000:3000 qhinhprd.azurecr.io/react-frontend:latest
